package com.adamford.eng.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF775A0B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDF9E)
val onPrimaryContainerLight = Color(0xFF261A00)
val secondaryLight = Color(0xFF6B5D3F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF5E0BB)
val onSecondaryContainerLight = Color(0xFF241A04)
val tertiaryLight = Color(0xFF4A6547)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCCEBC4)
val onTertiaryContainerLight = Color(0xFF072109)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F2)
val onBackgroundLight = Color(0xFF1F1B13)

val primaryDark = Color(0xFFE9C16C)
val onPrimaryDark = Color(0xFF3F2E00)
val primaryContainerDark = Color(0xFF5B4300)
val onPrimaryContainerDark = Color(0xFFFFDF9E)
val secondaryDark = Color(0xFFD8C4A0)
val onSecondaryDark = Color(0xFF3A2F15)
val secondaryContainerDark = Color(0xFF52452A)
val onSecondaryContainerDark = Color(0xFFF5E0BB)
val tertiaryDark = Color(0xFFB0CFAA)
val onTertiaryDark = Color(0xFF1D361C)
val tertiaryContainerDark = Color(0xFF334D31)
val onTertiaryContainerDark = Color(0xFFCCEBC4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF17130B)
val onBackgroundDark = Color(0xFFEBE1D4)

